development:
  adapter: postgresql
  encoding: unicode
  database: rsystem
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: rsystem_test
  pool: 5
  username: postgres
  password: root